### ISSUE TITLE
App could save its state also in browser storage

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/vyberova-rizeni#15]
Now when I fill in the form and hit refresh, I loose all data.

This could be avoided e.g. by caching in web browser storage or something like that.

**Comment by skodapetr** [comment]
Takže pokud tu stránku otevřeš příště znova, tak budeš muset udělat clear?
Jakože tady nejde o detail page ale i o celý ten seznam, jenž se tam drží. 

Je tedy třeba popsat-specifikovat jak přesně by se to měo chovat a za jaké situace.

**Comment by jakubklimek** [comment]
OK. Konkrétně mi jde o to, že v dnešní době člověk není zvyklý na to, že když odejde ze stránky (refresh), ztratí práci. To se teď děje. Ten local storage by tomu zabránil. Ale ano, má to pak i jiné efekty. Zřejmě by stačila kombinace tohoto, a nějakého "Clear all" tlačítka s konfirmací? ale je to teď minor.

**Comment by jakubklimek** [comment]
Appka bude jen prototyp. Tedy to není potřeba.
