### ISSUE TITLE
For codelists fall back to Czech when no translation available

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/vyberova-rizeni#16]
Instead of showing this:
![image](https://user-images.githubusercontent.com/718827/66378471-c7ae0880-e9b3-11e9-9251-c4a280074c26.png)
The codelists should fall back to Czech (e.g. there will never be a spanish version of the code list).

**Comment by skodapetr** [comment]
Btw. bylo by fajn být konzistentní s tagy, neb zatímco tohle je IMHO očividně bug, tak třeba změna specifikace pro datum nástupu a nebo zaslájí přihlášek bug není - neb špatná specifikace.
