### ISSUE TITLE
Přázdné položky se do výstupu nemají generovat.

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/vyberova-rizeni#18]
Přázdné položky se do výstupu nemají generovat. Nyní se genrují jako "null".

**Comment by skodapetr** [comment]
Co znamená prázdná položka?

**Comment by jakubklimek** [comment]
![image](https://user-images.githubusercontent.com/718827/66380945-a865aa00-e9b8-11e9-9e14-7382dab995ea.png)
![image](https://user-images.githubusercontent.com/718827/66380962-aef42180-e9b8-11e9-92d9-bff0e3cbc520.png)

**Comment by skodapetr** [comment]
Tohle se bude měnit s výstupním formátem, tedy bez jeho specifikace - pokud současný nepoužijeme jako výstupní, nemá moc ceny toto upravovat - neb se to může objevit zase.
