### ISSUE TITLE
Pracoviště, role apod nenašeptávají

### ISSUE THREAD

**Issue by martinnec** [mff-uk/vyberova-rizeni#31]
Ve formuláři, pokud začnu psát do Pracoviště, tak se nevyhledává v seznamu, ale rovnou se objeví "No data available". Mělo by se našeptat to, co obsahuje zadaný text (kdekoliv, non-case sensitive).

**Comment by skodapetr** [comment]
Mělo by být opraveno v fecb57346ed8f85c77a92e22a08c55c1fbdc3ed7
