### ISSUE TITLE
Ukazovat varování, že existují "nestažené" změny.

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/vyberova-rizeni#36]
Ukazovat varování, že existují "nestažené" změny.

**Comment by skodapetr** [comment]
Kde a v jaké situaci? Že by tam byl konzistentně v horní liště (kde je teď jen Výběrová řízení ) text, že jsou nestažené změny? 
S tím, že by to třeba změnilo barvu na žlutou?

**Comment by jakubklimek** [comment]
Jo. V detailu kdyz nekam neco napisu nebo neco zmenim, a v seznamu kdyz je v takovym stavu aspon jeden z inzeratu.
