### ISSUE TITLE
Nahradit "obor výzkumu" číselníky ISVaV a FORD

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/vyberova-rizeni#39]
![image](https://user-images.githubusercontent.com/718827/88367291-b6d85300-cd8b-11ea-8b53-22cef259fd67.png)
Obor výzkumu je teď volný text.
Dle OFN by měly být použity položky z číselníků:
- [Klasifikace oborů CEP & CEZ & RIV (ISVaV)](https://data.mvcr.gov.cz/datová-sada?iri=https%3A%2F%2Fdata.mvcr.gov.cz%2Fzdroj%2Fdatové-sady%2Fčíselníky%2Fklasifikace-oborů-isvav)
- [Klasifikace oborů výzkumu a vývoje FORD](https://data.mvcr.gov.cz/datová-sada?iri=https%3A%2F%2Fdata.mvcr.gov.cz%2Fzdroj%2Fdatové-sady%2Fčíselníky%2Fklasifikace-oborů-ford)

Je tedy třeba zrušit tento volný text, a přidat 2 číselníkové položky.

**Comment by skodapetr** [comment]
Tady je otázka jestli je tam dát napevno, nebo se dotazovat (bylo by třeba tu službu někde zavést).

**Comment by jakubklimek** [comment]
Je to prototyp - napevno.

**Comment by skodapetr** [comment]
No v současné době se dá použít obojí, máme distribuci kde je to zabalené a pak online demo kde je to dotazované. Tedy můžeme to udělat stejně. Což by asi bylo nejlepší a je podobné jako napevno.

**Comment by jakubklimek** [comment]
OK
