### ISSUE TITLE
Přejmenovat "obor" na "sekci"

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/vyberova-rizeni#40]
![image](https://user-images.githubusercontent.com/718827/88367583-7200ec00-cd8c-11ea-82f6-68a31c1cd57b.png)
Název položky "obor" je, obzvlášť v souvislosti s #39 matoucí. I do HTML se z toho generuje "sekce".

Je tedy třeba přejmenovat "Obor" na "Sekce", anglicky "Obor" na "School"

**Comment by skodapetr** [comment]
UI je vždy v češtině, jazyk se přepíná pouze pro data.

**Comment by skodapetr** [comment]
Na jakém místě je anglicky "obor" , jenž by bylo třeba změnit na "school" ?

**Comment by jakubklimek** [comment]
@skodapetr No praveze tam ani neni anglicky a mel by byt. Ted je tam taky Obor.

**Comment by jakubklimek** [comment]
dle domluvy je to v poho - anglicky totiz neni nic.
