### ISSUE TITLE
Smazat lze jen třetí jazyk, druhý ne.

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/vyberova-rizeni#5]
![image](https://user-images.githubusercontent.com/718827/66190276-f6627100-e68b-11e9-8456-3c336e56190d.png)

**Comment by skodapetr** [comment]
Otázkou je, proč není druhý jazyk EN, jak k tomu došlo?

**Comment by jakubklimek** [comment]
Pravděpodobně při nahrávání ze souboru
